services:
  streamlit-app:
    ports:
      - "8501:8501"
    build: ./streamlit_app
    command: entrypoint.sh
    volumes:
      - ./streamlit_app:/home/appuser:z
    env_file:
      - ./.env.dev
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env.dev
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata/

volumes:
  postgres_data: