services:
  nginx-proxy:
    container_name: nginx-proxy
    hostname: nginx-proxy
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    build: ./nginx
    ports:
      - "8080:8080"
    depends_on:
      - streamlit-app
      - db

  streamlit-app:
    ports:
      - "8501:8501"
    build: ./streamlit_app
    command: entrypoint.sh
    volumes:
      - ./streamlit_app:/home/appuser:z
    env_file:
      - ./.env.dev
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    depends_on:
      - db

  backend:
    ports:
      - "3000:3000"
    build: ./backend
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env.dev
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata/
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"

volumes:
  postgres_data: