services:
  nginx-proxy:
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    build: ./nginx
    ports:
      - "8080:8080"
    depends_on:
      - streamlit-app
      - db
      - backend

  streamlit-app:
    ports:
      - "8501:8501"
    build: ./streamlit_app
    command: entrypoint.sh
    volumes:
      - ./streamlit_app:/home/appuser:z
    env_file:
      - ./.env.dev
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    depends_on:
      - backend

  backend:
    ports:
      - "3000:3000"
    build: ./backend
    env_file:
      - ./.env.dev
    depends_on:
      - db
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"

  db:
    image: postgres:14
    build: ./postgres
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    env_file:
      - ./.env.dev
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata/

volumes:
  postgres_data: